- name: Assert no day2 nodes
  ansible.builtin.assert:
    that:
      - (groups['day2_workers'] | default([])) | length  == 0
    fail_msg: "use_agent_based_installer does not support day2 workers"

- name: Assert no partitions
  ansible.builtin.assert:
    that:
      - hostvars[item]['disks'] is not defined
    fail_msg: "Can not use partitions when using use_agent_based_installer"
  loop: "{{ groups['nodes'] | default([]) }}"

- name: Assert discovery is password hash is not defined
  ansible.builtin.assert:
    that:
      - hashed_discovery_password is not defined
    fail_msg: "hashed_discovery_password is not supported when use_agent_based_installer"

- name: Assert no OLM Operators
  ansible.builtin.assert:
    that:
      - install_lso is not defined
      - install_odf is not defined
      - install_cnv is not defined
    fail_msg: "Operator installion is not supported when use_agent_based_installer, you can use extra_manifests to deploy these operators"
