---
- name: Assert 'dhcp_range_first' and 'dhcp_range_last' are defined if needed
  assert:
    that:
      - hostvars['dns_host'][item] is defined
      - hostvars['dns_host'][item] | ansible.utils.ipaddr('bool') == True
    quiet: true
  when: hostvars['dns_host']['use_dhcp'] | default(false)
  loop:
    - dhcp_range_first
    - dhcp_range_last

- name: if DNS DHCP setup is enabled, ntp_server MUST be an IP for DNS config
  assert:
    that:
      - hostvars['dns_host']['ntp_server'] is defined
      - hostvars['dns_host']['ntp_server'] | ansible.utils.ipaddr('bool') == True
  when: hostvars['dns_host']['setup_dns_service'] | default(false) and hostvars['dns_host']['use_dhcp'] | default(false)

# All other DNS config is excluded for brevity at this time.
# It is taken from the cluster and/or AI configuration and is not DNS-specific so much is checked elsewhere.
