---
- name: Validate Inventory
  when: not (inventory_validated | default(False) | bool)
  delegate_to: "{{ validation_host | default('bastion') }}"
  block:
    - ansible.builtin.include_tasks: # noqa: unnamed-task
        file: required_vars.yml
        apply:
          tags: validate_required_vars
      tags: validate_required_vars

    - ansible.builtin.include_tasks: # noqa: unnamed-task
        file: cluster.yml
        apply:
          tags: validate_cluster
      tags: validate_cluster

    - ansible.builtin.include_tasks: # noqa: unnamed-task
        file: vendor.yml
        apply:
          tags: validate_vendor
      tags: validate_vendor

    - ansible.builtin.include_tasks: # noqa: unnamed-task
        file: ntp.yml
        apply:
          tags: validate_ntp
      tags: validate_ntp

    - ansible.builtin.include_tasks: # noqa: unnamed-task
        file: vms.yml
        apply:
          tags: validate_vms
      tags: validate_vms

    - ansible.builtin.include_tasks: # noqa: unnamed-task
        file: secrets.yml
        apply:
          tags: validate_secrets
      tags: validate_secrets

    - ansible.builtin.include_tasks: # noqa: unnamed-task
        file: prereqs.yml
        apply:
          tags: validate_prereqs
      tags: validate_prereqs

    - ansible.builtin.include_tasks: # noqa: unnamed-task
        file: proxy.yml
        apply:
          tags: validate_proxy_config
      tags: validate_proxy_config

    - ansible.builtin.include_tasks: # noqa: unnamed-task
        file: network.yml
        apply:
          tags: validate_network
      tags: validate_network

    - ansible.builtin.include_tasks: # noqa: unnamed-task
        file: day2.yml
        apply:
          tags: validate_day2
      tags: validate_day2

    - ansible.builtin.include_tasks: # noqa: unnamed-task
        file: partitions.yml
        apply:
          tags: validate_partitions
      tags: validate_partitions

    - ansible.builtin.include_tasks: # noqa: unnamed-task
        file: validate_pxe.yml
        apply:
          tags: validate_pxe
      tags: validate_pxe
      when: (setup_pxe_service | default(false)) | bool


- name: Record successful validation on all hosts
  ansible.builtin.set_fact:
    inventory_validated: true
  delegate_to: "{{ item }}"
  delegate_facts: true
  loop: "{{ groups['all'] + ['localhost'] }}"
