- name: Check ntp_server is valid
  assert:
    that:
      - hostvars['ntp_host']['ntp_server'] is defined
      - hostvars['ntp_host']['ntp_server'] | ansible.utils.ipaddr('bool') == True
  when: hostvars['ntp_host']['setup_ntp_service'] | default(false)
