- name: Check ntp_server is valid
  ansible.builtin.assert:
    that:
      - hostvars['ntp_host']['ntp_server'] is defined
      - hostvars['ntp_host']['ntp_server'] | ipaddr('bool')
  when: hostvars['ntp_host']['setup_ntp_service'] | default(false)
