- name: "Get VM {{ vm_name }} XML"
  community.libvirt.virt:
    name: "{{ vm_name }}"
    command: get_xml
  register: vm_info

- debug: # noqa unnamed-task
    var: vm_info
    verbosity: 1

- name: "Get files from {{ vm_name }} "
  community.general.xml:
    xmlstring: "{{ vm_info.get_xml }}"
    xpath: /domain/devices/disk/source
    content: attribute
  register: disks

- name: Update files_to_remove
  set_fact:
    files_to_remove: "{{ files_to_remove + (disks.matches | map(attribute='source.file') | list) }}"
