---
- name: Generate  ssh key pair
  ansible.builtin.import_playbook: playbooks/generate_ssh_key_pair.yml
  when: generate_ssh_keys | default(true)

- name: Create cluster
  ansible.builtin.import_playbook: playbooks/create_cluster.yml

- name: Generate discovery iso
  ansible.builtin.import_playbook: playbooks/generate_discovery_iso.yml

- name: Mount discovery iso for pxe
  ansible.builtin.import_playbook: playbooks/mount_discovery_iso_for_pxe.yml

- name: Boot iso
  ansible.builtin.import_playbook: playbooks/boot_iso.yml
  vars:
    boot_iso_hosts: masters,workers

- name: Install cluster
  ansible.builtin.import_playbook: playbooks/install_cluster.yml

- name: Monitor hosts
  ansible.builtin.import_playbook: playbooks/monitor_hosts.yml

- name: Monitor cluster
  ansible.builtin.import_playbook: playbooks/monitor_cluster.yml
