---
- name: Prereq facts check
  ansible.builtin.import_playbook: prereq_facts_check.yml

- name: Play to populate image_hashes for relevant images
  hosts: localhost
  roles:
    - get_image_hash

- name: Deploy NTP
  ansible.builtin.import_playbook: playbooks/deploy_ntp.yml

- name: Deploy HTTP store
  ansible.builtin.import_playbook: playbooks/deploy_http_store.yml

- name: Create VMs
  ansible.builtin.import_playbook: playbooks/create_vms.yml
  vars:
    nodes_to_process: "{{ groups['masters'] + groups['workers'] | default([]) }}"

- name: Deploy TFTP Service
  ansible.builtin.import_playbook: playbooks/deploy_tftp.yml

- name: Deploy DNS/DHCP Service
  ansible.builtin.import_playbook: playbooks/deploy_dns.yml

- name: Deploy Registry Service
  ansible.builtin.import_playbook: playbooks/deploy_registry.yml

- name: Deploy Assisted Installer Service
  ansible.builtin.import_playbook: playbooks/deploy_assisted_installer_onprem.yml

- name: Deploy Sushy Tools
  ansible.builtin.import_playbook: playbooks/deploy_sushy_tools.yml
