---
- name: Get kubeconfig
  hosts: bastion
  vars:
    secure: false
    ASSISTED_INSTALLER_BASE_URL: "{{ secure | ternary('https', 'http') }}://{{ hostvars['assisted_installer']['host'] }}:{{ hostvars['assisted_installer']['port'] }}/api/assisted-install/v2"
    URL_ASSISTED_INSTALLER_CLUSTER: "{{ ASSISTED_INSTALLER_BASE_URL }}/clusters/{{ cluster_id }}"
    kube_filename: "{{ kubeconfig_dest_filename | default(cluster_name + '-kubeconfig') }}"
    dest_dir: "{{ kubeconfig_dest_dir | default(ansible_env.HOME) }}"
    kubeconfig_path: "{{ dest_dir }}/{{ kube_filename }}"
    kubeadmin_vault_name: "{{ kubeadmin_dest_filename | default(cluster_name +'-kubeadmin.vault.yml') }}"
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  tasks:

    - name: Download kubeconfig
      get_url:
        url: "{{ URL_ASSISTED_INSTALLER_CLUSTER }}/downloads/credentials?file_name=kubeconfig"
        dest: "{{ kubeconfig_path }}"
        mode: 0664

    - name: Perform simple connectivity check with oc
      shell:
        cmd: "oc explain pods"

    - name: Check status of cluster operators
      block:
        - name: Wait up to 20 mins for cluster to become functional
          shell:
            cmd: oc wait clusteroperators --all --for=condition=Available --timeout=20m
      rescue:
        - name: Get better info for failure message
          shell: oc get clusteroperators
          register: co_result

        - fail:
            msg: |
              Cluster has not come up correctly:
                {{ co_result.stdout }}

    - name: Get credentials
      uri:
        url: "{{ URL_ASSISTED_INSTALLER_CLUSTER }}/credentials"
        return_content: yes
      register: credentials

    - name: Login to add token to kubeconfig
      shell:
        cmd: "oc login -u {{ credentials.json.username }} -p '{{ credentials.json.password }}'"

    - name: Save credentials to file
      copy:
        content: "{{ credentials.json | to_yaml }}"
        dest: "{{ dest_dir }}/{{ kubeadmin_vault_name }}"

    - name: Save credentials to vault
      shell:
        cmd: "ansible-vault encrypt --vault-password-file {{ kubeadmin_vault_password_file_path }} {{ dest_dir }}/{{ kubeadmin_vault_name }}"
      when: (kubeadmin_vault_password_file_path is defined) and (kubeadmin_vault_password_file_path is file)
