---
- name: Prerequisite Facts Check
  hosts: localhost
  connection: local
  strategy: free
  become: false
  gather_facts: false
  roles:
    - prereq_facts_check
  vars:
    ssh_public_check: "{{ not (generate_ssh_keys | default(true)) }}"
    mirror_certificate_check: "{{ ((use_local_mirror_registry | default(false)) | bool ) and not ((setup_registry_service | default(true)) | bool) }}"
