---
apiVersion: v1
kind: Template
labels:
  template: create-ns-template
metadata:
  name: create-ns-template
objects:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: ${NAMESPACE}
parameters:
- description: The namespace that will be created for imported cluster
  name: NAMESPACE
  value: "noknom-aicli"
  required: true
