---
apiVersion: v1
kind: Template
labels:
  template: create-agentclusterinstall-template
metadata:
  name: create-agentclusterinstall-template
objects:
- apiVersion: extensions.hive.openshift.io/v1beta1
  kind: AgentClusterInstall
  metadata:
    name: ${NAMESPACE}
    namespace: ${NAMESPACE}
  spec:
    apiVIP: ${APIVIP}
    clusterDeploymentRef:
      name: ${NAMESPACE}
    imageSetRef:
      name: openshift-v${OCPVERSION}
    ingressVIP: ${INGRESSVIP}
    platformType: ${PLATFORMTYPE}
    networking:
      clusterNetwork:
      - cidr: ${CLUSTERNETWORK}
        hostPrefix: 23
      serviceNetwork:
      - ${SERVICENETWORK}
    provisionRequirements:
      controlPlaneAgents: 3
    sshPublicKey: "${SSHKEY}"
parameters:
- description: The namespace that will be created for imported cluster
  name: NAMESPACE
  value: "noknom-aicli"
  required: true
- description: The API vip
  name: APIVIP
  value: "10.19.10.147"
  required: true
- description: The OCP version
  name: OCPVERSION
  value: "4.10.16"
  required: true
- description: The sshkey
  name: INGRESSVIP
  value: "10.19.10.148"
  required: true
- description: The sshkey
  name: PLATFORMTYPE
  value: "BareMetal"
  required: true
- description: The sshkey
  name: CLUSTERNETWORK
  value: "10.128.0.0/14"
  required: true
- description: The sshkey
  name: SERVICENETWORK
  value: "172.22.0.0/16"
  required: true
# - description: The sshkey
#   name: CONTROLPLANEAGENTS
#   value: 3
#   required: true
- description: The sshkey
  name: SSHKEY
  value: "xxxxxxxx"
  required: true
