---
apiVersion: v1
kind: Template
labels:
  template: create-clusterdeployment-template
metadata:
  name: create-clusterdeployment-template
objects:
- apiVersion: hive.openshift.io/v1
  kind: ClusterDeployment
  metadata:
    name: ${NAMESPACE}
    namespace: ${NAMESPACE}
  spec:
    baseDomain: ${BASEDOMAIN}
    clusterInstallRef:
      group: extensions.hive.openshift.io
      kind: AgentClusterInstall
      name: ${NAMESPACE}
      version: v1beta1
    clusterMetadata:
      adminKubeconfigSecretRef:
        name: ${NAMESPACE}-admin-kubeconfig
      adminPasswordSecretRef:
        name: ${NAMESPACE}-admin-password
      clusterID: "${CLUSTERID}"
      infraID: "${INFRAID}"
    clusterName: ${CLUSTERNAME}
    installed: true
    platform:
      agentBareMetal:
        agentSelector:
          matchLabels:
            cluster-name: ${CLUSTERNAME}
    pullSecretRef:
      name: pull-secret
parameters:
- description: The namespace that will be created for imported cluster
  name: NAMESPACE
  value: "noknom-aicli"
  required: true
- description: The Base domain
  name: BASEDOMAIN
  value: "cloud.lab.eng.bos.redhat.com"
  required: true
- description: The OCP version
  name: CLUSTERID
  value: "8581800e-e3e6-41ae-a391-28c95e9166b1"
  required: true
- description: The sshkey
  name: INFRAID
  value: "crucible-fhcpd"
  required: true
- description: The sshkey
  name: CLUSTERNAME
  value: "crucible"
  required: true
