---
apiVersion: v1
kind: Template
labels:
  template: create-managedcluster-template
metadata:
  name: create-managedcluster-template
objects:
- apiVersion: cluster.open-cluster-management.io/v1
  kind: ManagedCluster
  metadata:
    name: ${NAMESPACE}
    labels:
      cloud: auto-detect
      vendor: auto-detect
  spec:
    hubAcceptsClient: true
parameters:
- description: The namespace that will be created for imported cluster
  name: NAMESPACE
  value: "noknom-aicli"
  required: true
