---
- name: DELL Power ON
  community.general.redfish_command:
    category: Systems
    command: PowerOn
    baseuri: "{{ hostvars[inventory_hostname]['bmc_address'] }}"
    username: "{{ hostvars[inventory_hostname]['bmc_user'] }}"
    password: "{{ hostvars[inventory_hostname]['bmc_password'] }}"

- block:
    - name: Set Dell OneTimeBoot VirtualCD (VCD-DVD)
      community.general.redfish_command:
        category: Systems
        command: SetOneTimeBoot
        bootdevice: VCD-DVD
        baseuri: "{{ hostvars[inventory_hostname]['bmc_address'] }}"
        username: "{{ hostvars[inventory_hostname]['bmc_user'] }}"
        password: "{{ hostvars[inventory_hostname]['bmc_password'] }}"
  rescue:
    - name: Set Dell OneTimeBoot VirtualCD (Cd)
      community.general.redfish_command:
        category: Systems
        command: SetOneTimeBoot
        bootdevice: Cd
        baseuri: "{{ hostvars[inventory_hostname]['bmc_address'] }}"
        username: "{{ hostvars[inventory_hostname]['bmc_user'] }}"
        password: "{{ hostvars[inventory_hostname]['bmc_password'] }}"

- block:
    - name: DELL Eject Virtual Media (if any)
      community.general.redfish_command:
        category: Manager
        command: VirtualMediaEject
        baseuri: "{{ hostvars[inventory_hostname]['bmc_address'] }}"
        username: "{{ hostvars[inventory_hostname]['bmc_user'] }}"
        password: "{{ hostvars[inventory_hostname]['bmc_password'] }}"
        virtual_media:
          image_url: "{{ boot_iso_url }}"
        resource_id: iDRAC.Embedded.1
  rescue:
    - name: Get Virtual Media information
      community.general.redfish_info:
        category: Manager
        command: GetVirtualMedia
        baseuri: "{{ hostvars[inventory_hostname]['bmc_address'] }}"
        username: "{{ hostvars[inventory_hostname]['bmc_user'] }}"
        password: "{{ hostvars[inventory_hostname]['bmc_password'] }}"
      register: result

    - name: Get blocking virtual_media
      set_fact:
        blocking_virtual_media:  "{{ result.redfish_facts.virtual_media.entries
          | flatten(levels=2)
          | selectattr('ConnectedVia', 'defined') | list
          | json_query('[?(
              ConnectedVia == `URI`
              && Image != null
              && (
                contains(MediaTypes, `CD`)
                || contains(MediaTypes, `DVD`)
                || contains(MediaTypes, `VCD-DVD`)
              )
            )]'
          ) | from_yaml
        }}"

    - debug: # noqa unnamed-task
        var: blocking_virtual_media
      when: debug | bool == True

    - name: Attempting to eject blocking media
      community.general.redfish_command:
        category: Manager
        command: VirtualMediaEject
        baseuri: "{{ hostvars[inventory_hostname]['bmc_address'] }}"
        username: "{{ hostvars[inventory_hostname]['bmc_user'] }}"
        password: "{{ hostvars[inventory_hostname]['bmc_password'] }}"
        virtual_media:
          image_url: "{{ item.Image }}"
        resource_id: iDRAC.Embedded.1
      loop: "{{ blocking_virtual_media }}"
      no_log: True

- name: DELL Insert Virtual Media
  community.general.redfish_command:
    category: Manager
    command: VirtualMediaInsert
    baseuri: "{{ hostvars[inventory_hostname]['bmc_address'] }}"
    username: "{{ hostvars[inventory_hostname]['bmc_user'] }}"
    password: "{{ hostvars[inventory_hostname]['bmc_password'] }}"
    virtual_media:
      image_url: '{{ boot_iso_url }}'
      media_types:
        - CD
        - DVD
    resource_id: iDRAC.Embedded.1

- name: DELL Restart system power gracefully
  community.general.redfish_command:
    category: Systems
    command: PowerGracefulRestart
    baseuri: "{{ hostvars[inventory_hostname]['bmc_address'] }}"
    username: "{{ hostvars[inventory_hostname]['bmc_user'] }}"
    password: "{{ hostvars[inventory_hostname]['bmc_password'] }}"
