---
- name: Setup AI Host
  become: true
  block:
    - name: Install podman
      ansible.builtin.package:
        name: podman
        state: present

    - name: Configure registry cert and pull_secret
      when: use_local_mirror_registry  | bool
      block:
        - name: Copy cert to pki directory
          ansible.builtin.copy:
            content: "{{ mirror_certificate }}"
            dest: /etc/pki/ca-trust/source/anchors/ai_registry.crt
            mode: 0660
            force: true
            backup: true

        - name: Update the CA trust files
          ansible.builtin.command:
            cmd: update-ca-trust extract

        - name: Create podman auth dir
          ansible.builtin.file:
            path: "{{ config_file_path }}/containers/"
            state: directory
            recurse: true
            mode: 0755

        - name: Copy pull_secrets file.
          ansible.builtin.copy:
            content: "{{ pull_secret }}"
            dest: "{{ config_file_path }}/containers/auth.json"
            mode: 0644
            remote_src: true


    - name: Open ports zone internal and public, for firewalld
      ansible.posix.firewalld:
        port: "{{ item.1 }}/tcp"
        permanent: true
        immediate: true
        state: enabled
        zone: "{{ item.0 }}"
      loop: "{{ ['internal', 'public'] | product(['8000', '8090', '8080', '8888']) | list }}"

    - name: Create directories for assisted-installer
      ansible.builtin.file:
        path: "{{ item }}"
        mode: 0775
        state: directory
      with_items:
        - "{{ assisted_installer_dir }}"
        - "{{ assisted_installer_data_dir }}"

    - name: Create directory for assisted-installer database
      ansible.builtin.file:
        path: "{{ assisted_installer_data_dir }}/postgresql"
        mode: 0775
        state: directory
        recurse: true

    - name: Create directory for assisted-installer images
      ansible.builtin.file:
        path: "{{ assisted_installer_data_dir }}/image_service"
        mode: 0775
        state: directory
        recurse: true

    - name: Template out assisted-installer files
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: 0644
        trim_blocks: true
        lstrip_blocks: true
      loop:
        - src: configmap.yml.j2
          dest: "{{ assisted_installer_dir }}/configmap.yml"
        - src: pod.yml.j2
          dest: "{{ assisted_installer_dir }}/pod.yml"

- name: Setup AI pod
  become: true
  environment:
    XDG_RUNTIME_DIR: "{{ config_file_path }}"
  block:
    - name: Gather info about specific pods
      containers.podman.podman_pod_info:
        name: assisted-installer
      register: ai_pod_details

    - name: Remove Assisted Installer Pod
      containers.podman.podman_pod:
        name: assisted-installer
        state: absent
      when: (ai_pod_details.pods | length) > 0

    - name: Set network_name
      ansible.builtin.set_fact:
        network_name: assisted_installer_network
      when: use_ipv6 | default(False)

    - name: Create ipv6 network
      containers.podman.podman_network:
        debug: true
        name: "{{ network_name }}"
        subnet: "{{ podman_ipv6_network_subnet }}"
        gateway: "{{ podman_ipv6_network_gateway }}"
        ipv6: true
        recreate: true
      when: use_ipv6 | default(False)
      become: true

    - name: Update podman_networks with ipv6
      ansible.builtin.set_fact:
        podman_networks:
          - "{{ network_name }}"
      when: network_name is defined

    - name: Play kube file
      containers.podman.podman_play:
        kube_file: "{{ assisted_installer_dir }}/pod.yml"
        configmap: "{{ assisted_installer_dir }}/configmap.yml"
        network: "{{ podman_networks | default(omit) }}"
        recreate: true
        state: created

- name: Setup assisted_installer service
  become: true
  block:
    - name: Copy the systemd service file
      ansible.builtin.copy:
        content: |
          [Unit]
          Description=Podman assisted_installer.service
          [Service]
          Restart=no
          ExecStart=/usr/bin/podman pod start assisted-installer
          ExecStop=/usr/bin/podman pod stop -t 10 assisted-installer
          KillMode=none
          Type=forking
          [Install]
          WantedBy=default.target
        dest: "/etc/systemd/system/assisted_installer.service"
        mode: 0644

    - name: Reload systemd service
      ansible.builtin.systemd:
        daemon_reexec: true
        scope: system

    - name: Enable assisted_installer.service
      ansible.builtin.systemd:
        name: assisted_installer
        enabled: true
        scope: system

    - name: Start assisted_installer.service
      ansible.builtin.systemd:
        name: assisted_installer
        state: started
        scope: system
