secure: false
ASSISTED_INSTALLER_HOST: "{{ hostvars['assisted_installer']['host'] | default(ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0])) }}"
ASSISTED_INSTALLER_PORT: "{{ hostvars['assisted_installer']['port'] | default(8090) }}"
ASSISTED_INSTALLER_BASE_URL: "{{ secure | ternary('https', 'http') }}://{{ ASSISTED_INSTALLER_HOST }}:{{ ASSISTED_INSTALLER_PORT }}/api/assisted-install/v2"
URL_ASSISTED_INSTALLER_CLUSTER: "{{ ASSISTED_INSTALLER_BASE_URL }}/clusters/{{ cluster_id }}"
kube_filename: "{{ kubeconfig_dest_filename | default(cluster_name + '-kubeconfig') }}"
dest_dir: "{{ kubeconfig_dest_dir | default(ansible_env.HOME) }}"
kubeconfig_path: "{{ dest_dir }}/{{ kube_filename }}"
kubeadmin_vault_name: "{{ kubeadmin_dest_filename | default(cluster_name +'-kubeadmin.vault.yml') }}"
dest_dir: "{{ kubeconfig_dest_dir | default(ansible_env.HOME) }}"
kubeadmin_vault_path: "{{ dest_dir }}/{{ kubeadmin_vault_name }}"
docker_config: "{{ dockerconfig }}"
