---
- name: HPE Power ON
  community.general.redfish_command:
    category: Systems
    command: PowerOn
    baseuri: "{{ hostvars[item]['bmc_address'] }}"
    username: "{{ hostvars[item]['bmc_user'] }}"
    password: "{{ hostvars[item]['bmc_password'] }}"

- name: HPE Eject Virtual Media (if any)
  community.general.redfish_command:
    category: Manager
    command: VirtualMediaEject
    baseuri: "{{ hostvars[item]['bmc_address'] }}"
    username: "{{ hostvars[item]['bmc_user'] }}"
    password: "{{ hostvars[item]['bmc_password'] }}"
    virtual_media:
      image_url: "{{ boot_iso_url }}"
    resource_id: 1
  ignore_errors: yes

# Redfish module doesn't appear to support setting both options at once which ILO requires
- name: Set HPE OneTimeBoot Hdd
  uri:
    url: "https://{{ hostvars[item]['bmc_address'] }}/redfish/v1/Systems/1"
    user: "{{ hostvars[item]['bmc_user'] }}"
    password: "{{ hostvars[item]['bmc_password'] }}"
    method: PATCH
    headers:
      content-type: application/json
      Accept: application/json
    body: '{"Boot":{"BootSourceOverrideEnabled":"Continuous","BootSourceOverrideTarget":"Hdd"}}'
    body_format: json
    force_basic_auth: yes
    validate_certs: no
    return_content: yes


- name: HPE Restart system power gracefully
  community.general.redfish_command:
    category: Manager
    command: PowerGracefulRestart
    baseuri: "{{ hostvars[item]['bmc_address'] }}"
    username: "{{ hostvars[item]['bmc_user'] }}"
    password: "{{ hostvars[item]['bmc_password'] }}"
