- name: Create network_config
  include_tasks: make_network_config.yml
  when: network_config is not defined

- name: process network_config
  import_role:
    name: process_nmstate

- name: apply nmstate config
  import_role:
    name: apply_nmstate
