---
# tasks file for disconnected_registry
- import_tasks: var_check.yml
  tags: create_registry

- import_tasks: prerequisites.yml
  tags:
    - create_registry

- import_tasks: set_mirror_cert.yml

- import_tasks: setup_registry.yml
  tags: create_registry

- import_tasks: retrieve_config.yml
  tags:
    - copy_config
