- name: Set kvm_nodes
  vars:
    all_kvm_nodes: {}
  set_fact:
    all_kvm_nodes: "{{ all_kvm_nodes | combine({
        hostvars[item]['vm_host']: (
          (all_kvm_nodes[hostvars[item]['vm_host']] | default([])) + (
            [{
              'name': item.startswith(cluster_name) | ternary(item, (cluster_name + '_' + item)),
              'uuid': hostvars[item]['uuid'] | default(''),
              'mac':  hostvars[item]['mac'],
              'memory': hostvars[item]['vm_spec']['ram_mib'] | default(vm_params[hostvars[item]['role']]['memory']),
              'vcpu': hostvars[item]['vm_spec']['cpu_cores'] | default(vm_params[hostvars[item]['role']]['vcpu']),
              'disk_size': hostvars[item]['vm_spec']['disk_size_gb'] | default(vm_params[hostvars[item]['role']]['disk_size']),
              'vm_host': hostvars[item]['vm_host'],
            }]
          )
        )
      })
     }}"
  loop: "{{ (groups['masters'] + groups['workers'] | default([])) | unique }}"
  when: hostvars[item]['vendor'] | lower == 'kvm'

- name: Distribute kvm_nodes for vm_host to that host
  set_fact:
    kvm_nodes: "{{ all_kvm_nodes[item] | default([]) }}"
  delegate_to: "{{ item }}"
  delegate_facts: true
  loop: "{{ groups['vm_hosts'] | default([]) }}"
