network_name: "net-{{ cluster_name }}"
path_base_dir: /home/redhat
vm_create_scripts_dir: "{{ path_base_dir }}/vm_create_scripts/"
qemu_user: "{{ ansible_user | default(ansible_env.USER) }}"

virt_packages:
  - python3
  - libvirt
  - virt-install
  - qemu-kvm
  - virt-manager
  - python3-pip
  - python3-lxml
  - python3-libvirt

images_dir: /var/lib/libvirt/images/
