---
- import_playbook: extract_agent_based_installer.yml
  when: agent_based_installer_path is not defined

- import_playbook: generate_ssh_key_pair.yml
  when: generate_ssh_keys | default(True) == True

- import_playbook: generate_manifests.yml
- import_playbook: generate_agent_iso.yml

- import_playbook: boot_iso.yml
  vars:
    boot_iso_hosts: masters,workers

- import_playbook: monitor_agent_based_installer.yml
