---
- name: Install and http_store service
  hosts: http_store
  vars:
    SETUP_HTTP_STORE_SERVICE: "{{ setup_http_store_service | default(True) }}"
  roles:
    - name: setup_http_store
      when: SETUP_HTTP_STORE_SERVICE == True
    - validate_http_store
