---
- name: Install and http_store service
  hosts: http_store
  gather_facts: false
  vars:
    SETUP_HTTP_STORE_SERVICE: "{{ setup_http_store_service | default(true) }}"
  pre_tasks:
    - name: Setup facts
      ansible.builtin.setup:
      when: SETUP_HTTP_STORE_SERVICE | bool
  roles:
    - role: setup_http_store
      when: SETUP_HTTP_STORE_SERVICE | bool
    - validate_http_store
