- name: Monitoring hosts installation
  hosts: masters, workers
  gather_facts: False
  strategy: free
  roles:
    - monitor_host
  vars:
    - ASSISTED_INSTALLER_HOST: "{{ hostvars['assisted_installer']['host'] }}"
    - ASSISTED_INSTALLER_PORT: "{{ hostvars['assisted_installer']['port'] }}"
    - CLUSTER_ID: "{{ cluster_id | default(hostvars['bastion']['cluster_id']) }}"
