- name: Prepare bridges
  become: true
  block:
    - name: Install needed network manager libs
      package:
        name:
          - NetworkManager-libnm
          - nm-connection-editor
        state: present

    - name: Create BM bridge
      community.general.nmcli:
        conn_name: "{{ bridge_name }}"
        type: bridge
        ifname: "{{ bridge_name }}"
        autoconnect: yes
        never_default4: yes
        stp: no
        ip4: "{{ vm_bridge_ip + '/' + vm_bridge_prefix }}"
        dns4: "{{ hostvars[inventory_hostname]['dns'] }}"
        state: present

    - name: Create bridge slave
      community.general.nmcli:
        conn_name: "{{ vm_bridge_interface }}_{{ bridge_name }}"
        type: bridge-slave
        ifname: "{{ vm_bridge_interface }}"
        hairpin: no
        master: "{{ bridge_name }}"
        autoconnect: yes
        state: present
      when: vlan_tag is not defined

    - name: Setup VLan tagged bridge slave
      shell:
        cmd: >
          /usr/bin/nmcli \
            connection add \
            type vlan \
            con-name {{ bridge_name }}.{{ vlan_tag }} \
            ifname {{ bridge_name }}.{{ vlan_tag }} \
            dev {{ vm_bridge_interface }} \
            id {{ vlan_tag }} \
            master {{ bridge_name }} \
            slave-type bridge
      when: vlan_tag is defined

    - name: Bring up bridge slave
      shell:
        cmd: /usr/bin/nmcli con up {{ bridge_name }}

    - name: Bring up bridge slave
      shell:
        cmd: /usr/bin/nmcli con up {{ vm_bridge_interface }}_{{ bridge_name }}
      when: vlan_tag is not defined

    - name: Bring up bridge vlan slave
      shell:
        cmd: /usr/bin/nmcli con up {{ bridge_name }}.{{ vlan_tag }}
      when: vlan_tag is defined
